/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoramatrices;

import javax.swing.JOptionPane;

/**
 *
 * @author perez
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sum = new javax.swing.JButton();
        res = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        div = new javax.swing.JButton();
        Traza = new javax.swing.JButton();
        Dete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sum.setText("+");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        res.setText("-");
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });

        mul.setText("*");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        Traza.setText("Traza");
        Traza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrazaActionPerformed(evt);
            }
        });

        Dete.setText("Determinante");
        Dete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sum)
                        .addGap(69, 69, 69)
                        .addComponent(res)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(div)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Traza)
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dete)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mul)
                        .addGap(38, 38, 38)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sum)
                    .addComponent(res)
                    .addComponent(mul))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(div)
                    .addComponent(Traza)
                    .addComponent(Dete))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        c = new Suma();
        JOptionPane.showMessageDialog(null, c.calculo(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el numero a sumar a la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz"))));
    }//GEN-LAST:event_sumActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        c = new Resta();
        JOptionPane.showMessageDialog(null, c.calculo(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el numero a restar a la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz"))));

    }//GEN-LAST:event_resActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        c = new Multiplicacion();
        JOptionPane.showMessageDialog(null, c.calculo(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el numero a multiplicar a la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz"))));

    }//GEN-LAST:event_mulActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        c = new Division();
        JOptionPane.showMessageDialog(null, c.calculo(Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese el numero a dividir a la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz"))));

    }//GEN-LAST:event_divActionPerformed

    private void DeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeteActionPerformed
        c = new Determinante();
        JOptionPane.showMessageDialog(null, c.calculo(0, Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz"))));
    }//GEN-LAST:event_DeteActionPerformed

    private void TrazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrazaActionPerformed
        c = new Traza();
        JOptionPane.showMessageDialog(null, c.calculo(0, Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz")), Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las dimensiones de la matriz"))));
    }//GEN-LAST:event_TrazaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    Calculo c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dete;
    private javax.swing.JButton Traza;
    private javax.swing.JButton div;
    private javax.swing.JButton mul;
    private javax.swing.JButton res;
    private javax.swing.JButton sum;
    // End of variables declaration//GEN-END:variables
}
